// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "LilDemon":return img`
......bbbb............
......cbbbb...........
....bbbcbbbcb.........
.....bbbcbbcbb........
....ccbbccbbbbb.......
....cccceecbbbb.......
....cccceeecbfb.......
....cc4cdedde.........
.....c4ededde.........
......cedddde.........
.......eddde..........
...eeeccceeee.........
..eeeeec6668ee........
.bbeeee66666ee........
.bbbeee66666cccbbbb...
bbbbffcc888ccccffffbb.
bbbffff88888fccfccffc.
eee.fff88888ffeeccccfb
eee..cc88888ffeeeccccb
eee..cc88888fcceefcccb
e44.ffeeeeccfcceefcccb
.444feeeeecccfccccccc.
.4411eeeeccceeccccccc.
..41111effceee.cccc...
....e1111.feee........
...eeee111feeee.......
...eeee....eeee.......
...bbbe....feee.......
..fccc.....fcc........
..fccc.....fcc........
.fccc......fcc........
.fccc......fccc.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
