// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "LilDemon":return img`
................
.fffffff........
ff22222ff.......
f2ff2222f.......
fffff22fffff....
..fdddbbbbbf....
..fdfffffffff...
..fbfdddbbbbf...
..fbfdfbfbfbf...
..fbfbfbfbfbf...
..fbfbfbfbfbf...
..fbfbbbbbbbf...
.ffffffffffff...
.fccc444444f....
.fccc4ffffff....
.fccc4fbbbbf....
.fccc4fbbbbf....
.fccc4fffbbf....
.f4444fffbff....
.ffffff.fff.....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
