// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "LilDemon":return img`
......................
......................
......................
......................
......cbbbb...........
....bbbcbbbcb.........
.....bbecbbceb........
....cceecceeebb.......
....cccceeceeeb.......
....cccceeecefb.......
....cc4cdedde.........
.....c4ededde.........
......cedddde.........
.......eddde..........
...eeefffeeee.........
..eeeeef666cee........
.bbeeee66666ee........
.bbbeee66666cccbbbb...
bbbbffffcccfcccffffbb.
bbbffffcccccfccfccffc.
eee.fffcccccffeeccccfb
eee..ffcccccffeeeccccb
eee..ffcccccfcceefcccb
e44.ffeeeeccfcceefcccb
.444feeeeecccfccccccc.
.4411eeeeccceeccccccc.
..41111effceee.cccc...
....e1111.feee........
...eeee111feeee.......
...eeee....eeee.......
...bbbe....feee.......
..fccc.....fcc........
..fccc.....fcc........
.fccc......fcc........
.fccc......fccc.......
`;
            case "image2":
            case "asd":return img`
......................
......................
......................
..........b...........
..........bbb.........
.........cbbbbc.......
........bbcbbbcb......
........bbecbbeeb.....
.......cceecceeebb....
.......cccceeceebb.1..
......eeccceeeeeb..11.
.......cc4cdedde...11.
........c4ededde..111.
.........cedddde..111.
..........eddde...11..
.........eeeeeeebb11..
........eeeecccef111b.
........eeeecccef111c.
........eebbccccc44ccb
........fbbbbeee444ecb
........fbbbbeee44eecb
........ffbbbbee44eccb
.........fcccccfbcccc.
.........feeeeefccccc.
.........eeeeeeeccc...
.........eeeeeee......
.....ccceeeeeeee......
.....ccceeeeeee.......
....cccfeeeeeee.......
....ccf....eeee.......
....cc......bbb.......
............fcc.......
............fcc.......
............fccc......
............fccc......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
