scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleRedCrystal, function (sprite2, location2) {
    game.gameOver(false)
    game.setGameOverEffect(false, effects.melt)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (demon.x == 0) {
        demon.vy = 5
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleBlueCrystal, function (sprite, location) {
    game.gameOver(true)
    game.setGameOverEffect(true, effects.confetti)
})
let demon: Sprite = null
scene.setBackgroundColor(9)
demon = sprites.create(assets.image`LilDemon`, SpriteKind.Player)
scene.cameraFollowSprite(demon)
controller.moveSprite(demon, 100, 0)
tiles.setCurrentTilemap(tilemap`level0`)
demon.ay = 500
game.onUpdate(function () {
    demon.setImage(assets.image`LilDemon`)
    if (demon.vy < 0) {
        demon.setImage(img`
            ..............bbbb...........
            ..............cbbbb..........
            ............bbbcbbbcb........
            .............bbecbbeeb.......
            ............cceecceeebb......
            ............cccceeceeebb.....
            ...........ccccceeeceff......
            ............cc4cdedde........
            .............c4ededde........
            ..............cedddde........
            ...............eddde.........
            ...........eeefffeeee..bbb...
            ........bbbeeeef666ceeffffcb.
            ......bbbbbeeee66666eefffffb.
            ...44eeebbbbeee66666cceeffffb
            ..4444eee..fffffffffcceeeeffb
            ..114......fffffffff..cceeffb
            ..11.......eeeeeeff...ccccffc
            .111b......eeeeeeeee....ccccc
            .11bbb.....eeeeeeeeee....ccc.
            111bbbb....eebbbceeee........
            11bbbbb......cccfeeee........
            1bbbbbb......cccfeee.........
            1bbbbb........ccceee.........
            ..bbbb........cccee..........
            ..............cffee..........
            ...............fff...........
            ...............fff...........
            ...............fff...........
            ...............fff...........
            ................ff...........
            .............................
            .............................
            .............................
            .............................
            `)
    } else if (demon.vy > 0) {
        demon.setImage(img`
            .......b................
            ......bbbb..............
            ......cbbbb.............
            ....bbbebbbcb...........
            .....bbecbbceb..........
            ....cceecceeebb.........
            ...ccccceeceeeb.........
            ....cccceeeceffb........
            ....cc4cdedde...........
            .....c4ededde...........
            ......cedddde..ccbbbbbb.
            .......eddde..ccfffffbbb
            ...eeefffeeee.cffffffffb
            ..bbbeef666ceefffffffffb
            bbbbbee66666eeffccccccfb
            bbbbbbe66666ccffccccccfb
            bbbbbbffccccccffcccccccb
            .eeefffcccccfcffceeccccb
            ..eeeffcccccffeeeeefcccb
            ...444ffcccccfeeeeefcccb
            ...44411cccccfeeccccccc.
            ....4411111ccf.cccccccc.
            ......ee11111e...cccc...
            ......eeeeee11e.........
            ......eeeeeeeee.........
            .......eeeeceee.........
            ........eeecee..........
            ........eeeeff..........
            .........eeeff..........
            .........ebbff..........
            .........bccf...........
            ..........ccc...........
            ..........fcc...........
            ..........fccc..........
            ...........ccc..........
            `)
    } else if (demon.x % 2 == 0) {
        demon.setImage(img`
            .......................
            .......................
            .......................
            .......................
            ...........b...........
            ...........bbb.........
            ..........cbbbbc.......
            .........bbcbbbcb......
            .........bbecbbeeb.....
            ........cceecceeebb....
            ........cccceeceebb.1..
            .......eeccceeeeeb..11.
            ........cc4cdedde...11.
            .........c4ededde..111.
            ..........cedddde..111.
            ...........eddde...11..
            ..........eeeeeeebb11..
            .........eeeecccef111b.
            .........eeeecccef111c.
            .........eebbccccc44ccb
            .........fbbbbeee444ecb
            .........fbbbbeee44eecb
            .........ffbbbbee44eccb
            ..........fcccccfbcccc.
            ..........feeeeefccccc.
            ..........eeeeeeeccc...
            ..........eeeeeee......
            ......ccceeeeeeee......
            ......ccceeeeeee.......
            .....cccfeeeeeee.......
            .....ccf....eeee.......
            .....cc......bbb.......
            .............fcc.......
            .............fcc.......
            .............fccc......
            `)
    } else {
    	
    }
    if (demon.vx < 0) {
        demon.image.flipX()
    }
})
